### ISSUE TITLE
Review & Reconciliation of Blockchain Commons Security Services Contract?

### ISSUE THREAD

**Issue by ChristopherA** [disclose/list#226]
Blockchain Commons is an open infrastructure organization that both offers security review services (largely security architecture reviews and risk/threat models, but rarely code reviews), and will be asking others to review our own code.

In spirit of open development, in addition of sharing our code, we are also sharing our best practices and legal templates. We have just released the first draft of our "security services contract" https://github.com/BlockchainCommons/Open-Development/tree/master/security-services-contract which is intended to be used in future contracts by others of us, but also when we ask others to review our work.

I'd very much be interested in reconciling our contract with the language and concerns of raised by this community, and thus improve it for use by our community. Issues and PRs welcome!

**Comment by codingo** [comment]
Closing as spam as this doesn't appear to have any direct correllation to disclose.io

**Comment by ChristopherA** [comment]
This isn’t spam, but closely related. We are defining rules in our agreement that allow us to disclose vulnerabilities despite NDAs, and be able to share some details in research papers. The problem is that most companies asking for paid security reviews want the results to be secret under NDA but as responsible members of the community we can’t do that.

So our goal is to say what we do if we find a vulnerability in code or products & services available to the public. We will report as per your vulnerability policy, but if you don’t have one here is what we will default to.

As your project is also defining best practices for vulnerability policies, it would be useful to see if we can compare and align the disclosure policies.

We hope more security reviewers will ask to not be held under NDA in their contracts with companies, and by offers a “standard” that others can point to that they can get these security review contracts accepted by companies.

I urge you to consider looking out what we are doing, suggest changes to make consideration of what your advocacy is doing, and also help contract-based security researchers in addition to bug-bounty security reviewers change the status quo.

I urge you to keep this issue open until it can be replaced by a better more concrete solution.
